name: ci

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Format and Lint Check
        run: make format-lint-check

      - name: Test and Coverage
        timeout-minutes: 5
        run: make test-coverage

      - name: Diff Coverage
        run: make diff-coverage

      - uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            coverage.xml
            test-results.xml
            htmlcov/
            diff_cover_report.html

      - name: Test
        timeout-minutes: 5
        run: make test
